param(
    [string]$ProjectRoot = (Resolve-Path "$PSScriptRoot\..").Path,
    [string]$RecipePath = "assembly\mvp-import-flow.recipe.json",
    [string]$ManifestPath = "kits\form-analysis.kit-manifest.json",
    [string]$OutputRoot = "generated\mvp-import-flow",
    [switch]$DryRun
)

$ErrorActionPreference = "Stop"

function Read-JsonUtf8([string]$Path) {
    return Get-Content -Raw -Encoding UTF8 $Path | ConvertFrom-Json
}

function Add-UniquePath([System.Collections.Generic.List[string]]$List, [string]$Path) {
    if (-not [string]::IsNullOrWhiteSpace($Path) -and -not $List.Contains($Path)) {
        $List.Add($Path)
    }
}

function Add-KitWithDependencies([string]$KitId) {
    if ($resolvedKitIds.Contains($KitId)) {
        return
    }
    if (-not $kitMap.ContainsKey($KitId)) {
        throw "Kit not found: $KitId"
    }
    $kit = $kitMap[$KitId]
    foreach ($dependency in @($kit.dependencies)) {
        Add-KitWithDependencies $dependency
    }
    $resolvedKitIds.Add($KitId)
}

function Add-KitSources($Kit) {
    foreach ($path in @($Kit.frontend.pages) + @($Kit.frontend.components) + @($Kit.frontend.services) + @($Kit.frontend.hooks) + @($Kit.frontend.shellFiles)) {
        Add-UniquePath $sourcePaths $path
    }
    foreach ($path in @($Kit.backend.routers) + @($Kit.backend.core) + @($Kit.backend.services) + @($Kit.backend.models)) {
        Add-UniquePath $sourcePaths $path
    }
}

function Copy-SourcePath([string]$RelativePath) {
    $sourcePath = Join-Path $sourceAppRoot $RelativePath
    if (-not (Test-Path $sourcePath)) {
        $missingSources.Add($RelativePath)
        return
    }

    $targetPath = Join-Path $outputSourceRoot $RelativePath
    $targetParent = Split-Path -Parent $targetPath
    if (-not (Test-Path $targetParent)) {
        New-Item -ItemType Directory -Force $targetParent | Out-Null
    }

    Copy-Item -LiteralPath $sourcePath -Destination $targetPath -Recurse -Force
    $copiedSources.Add($RelativePath)
}

function Write-ExtractionReadme {
    $readmePath = Join-Path $outputFullPath "README.md"
    $contentLines = @(
        '# MVP Import Flow Extraction',
        '',
        'Generated by `tools/extract-mvp-flow.ps1`.',
        '',
        'Target flow:',
        '',
        '```text',
        'tenant-auth-kit -> upload-validation-kit -> import-pipeline-kit -> station-data-link-kit',
        '```',
        '',
        'This output is the first MVP extraction slice for checking source files, kit boundaries, and recomposition work.',
        'It is not yet a deployable application.',
        '',
        'Backend routers are registered through `backend/app/core/backend_router_registry.py`.',
        '',
        '## Extracted Kits',
        ''
    )
    $contentLines += $resolvedKitIds
    $contentLines += @(
        '',
        '## Next Steps',
        '',
        '1. Create the frontend tab registry.',
        '2. Split `UploadPage` into page shell, workflow state, API client, and view components.',
        '3. Add recipe schema validation.',
        '4. Add DB assembly planning for models, migrations, seeds, and env vars.',
        '5. Add MVP smoke tests.'
    )
    $content = $contentLines -join [Environment]::NewLine
    Set-Content -Encoding UTF8 $readmePath $content
}

$manifest = Read-JsonUtf8 (Join-Path $ProjectRoot $ManifestPath)
$recipe = Read-JsonUtf8 (Join-Path $ProjectRoot $RecipePath)

$kitMap = @{}
foreach ($kit in $manifest.kits) {
    $kitMap[$kit.id] = $kit
}

$resolvedKitIds = New-Object System.Collections.Generic.List[string]
$sourcePaths = New-Object System.Collections.Generic.List[string]
$copiedSources = New-Object System.Collections.Generic.List[string]
$missingSources = New-Object System.Collections.Generic.List[string]

foreach ($kitId in @($recipe.enabledKits)) {
    Add-KitWithDependencies $kitId
}

foreach ($kitId in $resolvedKitIds) {
    Add-KitSources $kitMap[$kitId]
}

$sourceSystemPath = $manifest.sourceSystem.path
$sourceAppRoot = Join-Path $sourceSystemPath $manifest.sourceSystem.appRoot
$outputFullPath = Join-Path $ProjectRoot $OutputRoot
$outputSourceRoot = Join-Path $outputFullPath $manifest.sourceSystem.appRoot

if ($DryRun) {
    $report = [ordered]@{
        generatedAt = (Get-Date).ToString("s")
        recipe = $recipe.name
        sourceSystem = $sourceSystemPath
        resolvedKits = $resolvedKitIds.ToArray()
        plannedSources = $sourcePaths.ToArray()
        output = $outputFullPath
        dryRun = $true
    }

    $report | ConvertTo-Json -Depth 20
    Write-Host "Dry run only. Planned sources: $($sourcePaths.Count)"
    return
}

if (Test-Path $outputFullPath) {
    Remove-Item -LiteralPath $outputFullPath -Recurse -Force
}

New-Item -ItemType Directory -Force $outputSourceRoot | Out-Null

foreach ($path in $sourcePaths) {
    Copy-SourcePath $path
}

Write-ExtractionReadme

$mvpResolvedPlanPath = "assembly\mvp-resolved-plan.json"
$resolveRecipeTool = Join-Path $ProjectRoot "tools\resolve-recipe.ps1"
$generateRegistryTool = Join-Path $ProjectRoot "tools\generate-backend-registry.ps1"
$applyRegistryTool = Join-Path $ProjectRoot "tools\apply-backend-registry.ps1"
$applyUploadRefactorTool = Join-Path $ProjectRoot "tools\apply-upload-page-refactor.ps1"

if ((Test-Path $resolveRecipeTool) -and (Test-Path $generateRegistryTool) -and (Test-Path $applyRegistryTool)) {
    & $resolveRecipeTool `
        -ProjectRoot $ProjectRoot `
        -RecipePath $RecipePath `
        -ManifestPath $ManifestPath `
        -OutputPath $mvpResolvedPlanPath | Out-Null

    & $generateRegistryTool `
        -ProjectRoot $ProjectRoot `
        -ResolvedPlanPath $mvpResolvedPlanPath `
        -OutputDirectory "assembly\backend-registry-mvp" | Out-Null

    $generateMiddlewareRegistryTool = Join-Path $ProjectRoot "tools\generate-backend-middleware-registry.ps1"
    if (Test-Path $generateMiddlewareRegistryTool) {
        & $generateMiddlewareRegistryTool `
            -ProjectRoot $ProjectRoot `
            -ResolvedPlanPath $mvpResolvedPlanPath `
            -OutputDirectory "assembly\backend-middleware-registry-mvp" | Out-Null
    }

    $generatedAppRoot = Join-Path $OutputRoot $manifest.sourceSystem.appRoot
    & $applyRegistryTool `
        -ProjectRoot $ProjectRoot `
        -GeneratedAppRoot $generatedAppRoot `
        -RegistrySource "assembly\backend-registry-mvp\backend_router_registry.py" | Out-Null
}

if (Test-Path $applyUploadRefactorTool) {
    & $applyUploadRefactorTool `
        -ProjectRoot $ProjectRoot `
        -GeneratedAppRoot (Join-Path $OutputRoot $manifest.sourceSystem.appRoot) | Out-Null
}

$report = [ordered]@{
    generatedAt = (Get-Date).ToString("s")
    recipe = $recipe.name
    sourceSystem = $sourceSystemPath
    resolvedKits = $resolvedKitIds.ToArray()
    copiedSources = $copiedSources.ToArray()
    missingSources = $missingSources.ToArray()
    output = $outputFullPath
}

$reportPath = Join-Path $outputFullPath "extraction-report.json"
$report | ConvertTo-Json -Depth 20 | Set-Content -Encoding UTF8 $reportPath

Write-Host "MVP extraction written to $outputFullPath"
Write-Host "Copied sources: $($copiedSources.Count)"
Write-Host "Missing sources: $($missingSources.Count)"
