param(
    [string]$ProjectRoot = (Resolve-Path "$PSScriptRoot\..").Path,
    [string]$RecipePath = "assembly\form-analysis-original.recipe.json",
    [string]$ManifestPath = "kits\form-analysis.kit-manifest.json",
    [string]$IRPath = "",
    [string]$OutputDirectory = "assembly\frontend-registry"
)

$ErrorActionPreference = "Stop"

function Read-JsonUtf8([string]$Path) {
    return Get-Content -Raw -Encoding UTF8 $Path | ConvertFrom-Json
}

function ConvertTo-TypeScriptString([string]$Value) {
    if ([string]::IsNullOrWhiteSpace($Value)) {
        return "undefined"
    }
    return "'" + $Value.Replace("\", "\\").Replace("'", "\'") + "'"
}

function ConvertTo-TypeScriptStringArray([object[]]$Values) {
    $items = @($Values | Where-Object { -not [string]::IsNullOrWhiteSpace([string]$_) } | ForEach-Object { ConvertTo-TypeScriptString ([string]$_) })
    return "[" + ($items -join ", ") + "]"
}

$outputFullPath = Join-Path $ProjectRoot $OutputDirectory

if (-not (Test-Path $outputFullPath)) {
    New-Item -ItemType Directory -Force $outputFullPath | Out-Null
}

$tabs = New-Object System.Collections.Generic.List[object]
$irFullPath = if ([string]::IsNullOrWhiteSpace($IRPath)) { "" } else { Join-Path $ProjectRoot $IRPath }
if (-not [string]::IsNullOrWhiteSpace($irFullPath) -and (Test-Path $irFullPath)) {
    $ir = Read-JsonUtf8 $irFullPath
    foreach ($nav in @($ir.frontend.navigation)) {
        $tabs.Add([ordered]@{
            tab = $nav.tab
            labelKey = $nav.labelKey
            kit = $nav.kit
            visibleWhen = $nav.visibleWhen
            pages = @($nav.pages)
            services = @($nav.services)
        })
    }
} else {
    $recipe = Read-JsonUtf8 (Join-Path $ProjectRoot $RecipePath)
    $manifest = Read-JsonUtf8 (Join-Path $ProjectRoot $ManifestPath)

    $kitMap = @{}
    foreach ($kit in @($manifest.kits)) {
        $kitMap[[string]$kit.id] = $kit
    }

    foreach ($nav in @($recipe.frontendNavigation)) {
        if (-not @($recipe.enabledKits).Contains([string]$nav.kit)) {
            continue
        }

        $kit = $kitMap[[string]$nav.kit]
        $tabs.Add([ordered]@{
            tab = $nav.tab
            labelKey = $nav.labelKey
            kit = $nav.kit
            visibleWhen = $nav.visibleWhen
            pages = @($kit.frontend.pages)
            services = @($kit.frontend.services)
        })
    }
}

$jsonPath = Join-Path $outputFullPath "frontend-tab-registry.json"
$tabs | ConvertTo-Json -Depth 20 | Set-Content -Encoding UTF8 $jsonPath

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("// Generated by tools/generate-frontend-registry.ps1")
$lines.Add("export type FrontendTabRegistration = {")
$lines.Add("  tab: string;")
$lines.Add("  labelKey: string;")
$lines.Add("  kit: string;")
$lines.Add("  visibleWhen?: string;")
$lines.Add("  pages: string[];")
$lines.Add("  services: string[];")
$lines.Add("};")
$lines.Add("")
$lines.Add("export const frontendTabRegistry: FrontendTabRegistration[] = [")
foreach ($tab in $tabs) {
    $pages = ConvertTo-TypeScriptStringArray @($tab.pages)
    $services = ConvertTo-TypeScriptStringArray @($tab.services)
    $lines.Add("  {")
    $lines.Add("    tab: $(ConvertTo-TypeScriptString ([string]$tab.tab)),")
    $lines.Add("    labelKey: $(ConvertTo-TypeScriptString ([string]$tab.labelKey)),")
    $lines.Add("    kit: $(ConvertTo-TypeScriptString ([string]$tab.kit)),")
    if (-not [string]::IsNullOrWhiteSpace([string]$tab.visibleWhen)) {
        $lines.Add("    visibleWhen: $(ConvertTo-TypeScriptString ([string]$tab.visibleWhen)),")
    }
    $lines.Add("    pages: $pages,")
    $lines.Add("    services: $services,")
    $lines.Add("  },")
}
$lines.Add("];")

$tsPath = Join-Path $outputFullPath "frontendTabRegistry.ts"
$lines -join [Environment]::NewLine | Set-Content -Encoding UTF8 $tsPath

Write-Host "Frontend tab registry JSON written to $jsonPath"
Write-Host "Frontend tab registry TypeScript written to $tsPath"
