param(
    [string]$ProjectRoot = (Resolve-Path "$PSScriptRoot\..").Path,
    [string]$ResolvedPlanPath = "assembly\resolved-plan.json",
    [string]$IRPath = "",
    [string]$OutputDirectory = "assembly\backend-middleware-registry"
)

$ErrorActionPreference = "Stop"

function Read-JsonUtf8([string]$Path) {
    return Get-Content -Raw -Encoding UTF8 $Path | ConvertFrom-Json
}

function ConvertTo-PythonString([string]$Value) {
    if ([string]::IsNullOrWhiteSpace($Value)) {
        return "None"
    }
    return "'" + $Value.Replace("\", "\\").Replace("'", "\'") + "'"
}

function ConvertTo-SettingsName([string]$Value) {
    if ([string]::IsNullOrWhiteSpace($Value)) {
        return ""
    }
    return $Value.ToLowerInvariant()
}

$resolvedPlanFullPath = Join-Path $ProjectRoot $ResolvedPlanPath
$outputFullPath = Join-Path $ProjectRoot $OutputDirectory

$irFullPath = if ([string]::IsNullOrWhiteSpace($IRPath)) { "" } else { Join-Path $ProjectRoot $IRPath }
if (-not [string]::IsNullOrWhiteSpace($irFullPath) -and (Test-Path $irFullPath)) {
    $ir = Read-JsonUtf8 $irFullPath
    $registrations = @($ir.backend.middlewareRegistrations)
} else {
    $plan = Read-JsonUtf8 $resolvedPlanFullPath
    $registrations = @($plan.backendMiddlewareRegistrations)
}

# Filter out registrations whose Python source file does not exist in the assembled backend.
# Mirrors generate-backend-registry.ps1's router filter: only applies when $OutputDirectory
# points at the assembled tree (assemble-system.ps1's call site).
$assembledBackendDir = Join-Path (Split-Path (Split-Path $outputFullPath -Parent) -Parent) "backend"
if (Test-Path $assembledBackendDir) {
    $registrations = @($registrations | Where-Object {
        $moduleRelPath = ([string]$_.module).Replace('.', '\') + '.py'
        $exists = Test-Path (Join-Path $assembledBackendDir $moduleRelPath)
        if (-not $exists) {
            Write-Host "generate-backend-middleware-registry: skipping $([string]$_.module) (source not found in assembled backend)"
        }
        $exists
    })
}

if (-not (Test-Path $outputFullPath)) {
    New-Item -ItemType Directory -Force $outputFullPath | Out-Null
}

$jsonPath = Join-Path $outputFullPath "backend-middleware-registry.json"
$registrations | ConvertTo-Json -Depth 20 | Set-Content -Encoding UTF8 $jsonPath

$lines = New-Object System.Collections.Generic.List[string]
$lines.Add("# Generated by tools/generate-backend-middleware-registry.ps1")
$lines.Add("from __future__ import annotations")
$lines.Add("")
$lines.Add("from dataclasses import dataclass")
$lines.Add("from importlib import import_module")
$lines.Add("from typing import Any")
$lines.Add("")
$lines.Add("")
$lines.Add("@dataclass(frozen=True)")
$lines.Add("class BackendMiddlewareRegistration:")
$lines.Add("    kit: str")
$lines.Add("    module: str")
$lines.Add("    symbol: str")
$lines.Add("    feature_flag: str | None = None")
$lines.Add("")
$lines.Add("")
$lines.Add("MIDDLEWARE_REGISTRY = [")

foreach ($registration in $registrations) {
    $lines.Add("    BackendMiddlewareRegistration(")
    $lines.Add("        kit=$(ConvertTo-PythonString ([string]$registration.kit)),")
    $lines.Add("        module=$(ConvertTo-PythonString ([string]$registration.module)),")
    $lines.Add("        symbol=$(ConvertTo-PythonString ([string]$registration.symbol)),")
    $lines.Add("        feature_flag=$(ConvertTo-PythonString (ConvertTo-SettingsName ([string]$registration.featureFlag))),")
    $lines.Add("    ),")
}

$lines.Add("]")
$lines.Add("")
$lines.Add("")
$lines.Add("def register_backend_middlewares(app: Any, *, settings: Any) -> None:")
$lines.Add("    # Registered in list order; the LAST call to app.middleware() becomes the")
$lines.Add("    # INNERMOST layer, i.e. it runs after every middleware main.py adds directly")
$lines.Add("    # (api_key_auth_middleware, audit_events_middleware), so request.state.is_admin /")
$lines.Add("    # actor_role are already resolved by the time a kit-contributed middleware runs.")
$lines.Add("    for item in MIDDLEWARE_REGISTRY:")
$lines.Add("        if item.feature_flag and not bool(getattr(settings, item.feature_flag.lower(), False)):")
$lines.Add("            continue")
$lines.Add("        module = import_module(item.module)")
$lines.Add("        func = getattr(module, item.symbol)")
$lines.Add("        app.middleware('http')(func)")
$lines.Add("")

$pythonPath = Join-Path $outputFullPath "backend_middleware_registry.py"
$lines -join [Environment]::NewLine | Set-Content -Encoding UTF8 $pythonPath

Write-Host "Backend middleware registry JSON written to $jsonPath"
Write-Host "Backend middleware registry Python written to $pythonPath"
