param(
    [string]$ProjectRoot = (Resolve-Path "$PSScriptRoot\..").Path,
    [string]$ManifestPath = "kits\form-analysis.kit-manifest.json",
    [string]$DaihuiSampleDirectory = "",
    [string]$OutputRoot = "build\kit-combination-tests",
    [switch]$AssembleAll
)

$ErrorActionPreference = "Stop"

function Read-JsonUtf8([string]$Path) {
    return Get-Content -Raw -Encoding UTF8 $Path | ConvertFrom-Json
}

function Write-JsonUtf8([string]$Path, [object]$Value) {
    $parent = Split-Path -Parent $Path
    if (-not (Test-Path $parent)) {
        New-Item -ItemType Directory -Force $parent | Out-Null
    }
    $Value | ConvertTo-Json -Depth 50 | Set-Content -Encoding UTF8 $Path
}

function Get-ArrayValue([object]$Value) {
    if ($null -eq $Value) { return @() }
    return @($Value)
}

function Get-KitClosure([string[]]$KitIds, [hashtable]$KitMap) {
    $closed = New-Object System.Collections.Generic.HashSet[string]

    function Add-WithDeps([string]$KitId) {
        if ([string]::IsNullOrWhiteSpace($KitId)) { return }
        if (-not $KitMap.ContainsKey($KitId)) {
            throw "Unknown kit in combination: $KitId"
        }
        if ($closed.Contains($KitId)) { return }

        foreach ($dep in Get-ArrayValue $KitMap[$KitId].dependencies) {
            Add-WithDeps ([string]$dep)
        }
        $null = $closed.Add($KitId)
    }

    foreach ($kitId in $KitIds) {
        Add-WithDeps $kitId
    }

    return @($closed)
}

function New-TestRecipe([string]$Name, [string[]]$EnabledKits, [object[]]$Navigation) {
    return [ordered]@{
        recipeVersion = "0.3.0"
        name = $Name
        displayName = "Kit Combination Test - $Name"
        description = "Generated by tools/test-kit-combinations.ps1"
        sourceManifest = "kits/form-analysis.kit-manifest.json"
        database = [ordered]@{
            engine = "postgresql"
            selectedByUserIntent = [ordered]@{
                dataCriticality = "production"
                needsTenantIsolation = $true
                needsDaihuiSchemaPack = $true
            }
            reasonForNonTechnicalUser = "Combination test uses the Daihui five-form schema pack."
        }
        enabledKits = @($EnabledKits)
        featureFlags = [ordered]@{
            MULTI_TENANT_ENABLED = $true
            AUTH_MODE = "api_key"
            USE_GENERIC_SCHEMA = $true
            PDF_SERVER_URL = "required"
            MOD_API_BASE_URL = "required"
            MOD_WEBHOOK_SECRET = "required"
        }
        frontendNavigation = @($Navigation)
        previewScenarios = @(
            [ordered]@{
                id = "daihui-five-form-smoke"
                label = "Daihui five-form DB schema smoke"
                sourceDirectory = $DaihuiSampleDirectory
                expectedForms = 5
            }
        )
        selectedSubfeatures = [ordered]@{}
        selectedSubfeatureOptions = [ordered]@{}
    }
}

function Test-DaihuiSamples([string]$SampleDirectory) {
    if (-not (Test-Path $SampleDirectory)) {
        throw "Daihui sample directory not found: $SampleDirectory"
    }

    $expectedFiles = @(
        "entry_horizontal.csv",
        "inspection_horizontal.csv",
        "material_horizontal.csv",
        "production_horizontal.csv",
        "quality_horizontal.csv"
    )

    $actualCsvFiles = @(Get-ChildItem -LiteralPath $SampleDirectory -File -Filter "*.csv")
    if ($actualCsvFiles.Count -ne 5) {
        throw "Daihui sample directory should contain exactly 5 CSV files; found $($actualCsvFiles.Count)"
    }

    foreach ($fileName in $expectedFiles) {
        $path = Join-Path $SampleDirectory $fileName
        if (-not (Test-Path $path)) {
            throw "Missing Daihui CSV sample: $path"
        }
        $rows = @(Import-Csv -LiteralPath $path -Encoding UTF8)
        if ($rows.Count -ne 1) {
            throw "Daihui CSV sample should contain exactly 1 data row: $fileName has $($rows.Count)"
        }
        $headers = @($rows[0].PSObject.Properties.Name)
        if ($headers.Count -lt 5) {
            throw "Daihui CSV sample has too few columns: $fileName"
        }
    }
}

function Assert-ResolvedPlan([object]$Plan, [string[]]$ExpectedKits, [string]$Name) {
    if (@($Plan.missing).Count -gt 0) {
        $missingJson = @($Plan.missing) | ConvertTo-Json -Depth 10
        throw "Resolved plan for $Name contains missing entries: $missingJson"
    }

    foreach ($kitId in $ExpectedKits) {
        if (-not @($Plan.resolvedKitOrder).Contains($kitId)) {
            throw "Resolved plan for $Name did not include expected kit: $kitId"
        }
    }

    if (-not @($Plan.resolvedKitOrder).Contains("platform-core-kit")) {
        throw "Resolved plan for $Name omitted platform-core-kit"
    }
}

function Assert-DaihuiDbPlan([string]$ProjectRoot, [string]$ResolvedPlanPath, [string]$Name) {
    & (Join-Path $ProjectRoot "tools\generate-db-plan.ps1") `
        -ProjectRoot $ProjectRoot `
        -ResolvedPlanPath $ResolvedPlanPath `
        -OutputDirectory "build\kit-combination-tests\db-plan-$Name" | Out-Null

    $dbPlan = Read-JsonUtf8 (Join-Path $ProjectRoot "build\kit-combination-tests\db-plan-$Name\db-assembly-plan.json")
    $inference = Read-JsonUtf8 (Join-Path $ProjectRoot "build\kit-combination-tests\db-plan-$Name\daihui-schema-inference.json")

    if (@($dbPlan.schemaVersions).Count -ne 5) {
        throw "DB plan for $Name should include 5 Daihui schema versions"
    }
    if (@($dbPlan.seedData.formDefinitions).Count -ne 5) {
        throw "DB plan for $Name should include 5 Daihui form definitions"
    }
    if (@($inference.forms).Count -ne 5) {
        throw "Daihui inference for $Name should include 5 forms"
    }
    foreach ($form in @($inference.forms)) {
        if ($form.rowCount -ne 1) {
            throw "Daihui inference for $Name should read 1 sample row from $($form.sampleFile); got $($form.rowCount)"
        }
    }
}

function Assert-AssemblyContract([string]$ProjectRoot, [string]$ResolvedPlanPath, [string]$Name, [string[]]$ExpectedKits) {
    $irPath = "build\kit-combination-tests\assembly-ir-$Name.json"
    & (Join-Path $ProjectRoot "tools\generate-assembly-ir.ps1") `
        -ProjectRoot $ProjectRoot `
        -ResolvedPlanPath $ResolvedPlanPath `
        -OutputPath $irPath | Out-Null

    $ir = Read-JsonUtf8 (Join-Path $ProjectRoot $irPath)
    if (@($ir.selectedKits).Count -lt $ExpectedKits.Count) {
        throw "Assembly IR for $Name has fewer selected kits than expected"
    }
    foreach ($kitId in $ExpectedKits) {
        if (-not @($ir.selectedKits | ForEach-Object { [string]$_.id }).Contains($kitId)) {
            throw "Assembly IR for $Name omitted expected kit: $kitId"
        }
    }
    if (-not $ir.database.baselines.daihuiFormSchema) {
        throw "Assembly IR for $Name is missing Daihui schema baseline"
    }
    if (@($ir.kitInstallPlan).Count -lt $ExpectedKits.Count) {
        throw "Assembly IR for $Name should include kit install entries"
    }
}

$manifestFullPath = Join-Path $ProjectRoot $ManifestPath
$manifest = Read-JsonUtf8 $manifestFullPath
$outputFullPath = Join-Path $ProjectRoot $OutputRoot

if ([string]::IsNullOrWhiteSpace($DaihuiSampleDirectory)) {
    $daihuiBaselinePath = Join-Path $ProjectRoot "assembly\baselines\daihui-form-schema.baseline.json"
    if (-not (Test-Path $daihuiBaselinePath)) {
        throw "DaihuiSampleDirectory was not provided and baseline was not found: $daihuiBaselinePath"
    }
    $daihuiBaseline = Read-JsonUtf8 $daihuiBaselinePath
    $DaihuiSampleDirectory = [string]$daihuiBaseline.sourceDirectory
}

if (Test-Path $outputFullPath) {
    Remove-Item -LiteralPath $outputFullPath -Recurse -Force
}
New-Item -ItemType Directory -Force $outputFullPath | Out-Null

Test-DaihuiSamples $DaihuiSampleDirectory

$kitMap = @{}
foreach ($kit in @($manifest.kits)) {
    $kitMap[[string]$kit.id] = $kit
}

$requiredKits = @($manifest.kits | Where-Object { $true -eq $_.required } | ForEach-Object { [string]$_.id })
$optionalKits = @($manifest.kits | Where-Object { $true -ne $_.required } | ForEach-Object { [string]$_.id })
if ($requiredKits.Count -eq 0) {
    throw "Manifest does not define required kits"
}

$capabilityScenarios = @(
    [ordered]@{ name = "required-only"; kits = @(); nav = @() },
    [ordered]@{ name = "upload-validation"; kits = @("upload-validation-kit"); nav = @([ordered]@{ tab = "upload"; labelKey = "tabs.upload"; kit = "upload-validation-kit" }) },
    [ordered]@{ name = "import-flow"; kits = @("upload-validation-kit", "import-pipeline-kit"); nav = @([ordered]@{ tab = "upload"; labelKey = "tabs.upload"; kit = "upload-validation-kit" }) },
    [ordered]@{ name = "query-traceability"; kits = @("query-traceability-kit"); nav = @([ordered]@{ tab = "query"; labelKey = "tabs.query"; kit = "query-traceability-kit" }) },
    [ordered]@{ name = "analytics"; kits = @("analytics-kit"); nav = @([ordered]@{ tab = "analytics"; labelKey = "tabs.analytics"; kit = "analytics-kit" }) },
    [ordered]@{ name = "station-admin"; kits = @("station-admin-kit"); nav = @([ordered]@{ tab = "admin"; labelKey = "tabs.admin"; kit = "station-admin-kit" }) },
    [ordered]@{ name = "audit-edit"; kits = @("audit-edit-kit"); nav = @([ordered]@{ tab = "audit"; labelKey = "tabs.audit"; kit = "audit-edit-kit" }) },
    [ordered]@{ name = "logs-ops"; kits = @("logs-ops-kit"); nav = @([ordered]@{ tab = "logs"; labelKey = "tabs.logs"; kit = "logs-ops-kit" }) },
    [ordered]@{ name = "generic-forms"; kits = @("generic-forms-kit"); nav = @([ordered]@{ tab = "forms"; labelKey = "tabs.forms"; kit = "generic-forms-kit" }) },
    [ordered]@{ name = "mod-subscription"; kits = @("mod-subscription-kit"); nav = @([ordered]@{ tab = "subscriptions"; labelKey = "tabs.subscriptions"; kit = "mod-subscription-kit" }) },
    [ordered]@{ name = "all-site-no-mod"; kits = @($optionalKits | Where-Object { $_ -ne "mod-subscription-kit" }); nav = @() },
    [ordered]@{ name = "all-site-with-mod"; kits = @($optionalKits); nav = @() }
)

$summary = New-Object System.Collections.Generic.List[object]
$recipeDir = Join-Path $outputFullPath "recipes"
$planDir = Join-Path $outputFullPath "plans"

foreach ($scenario in $capabilityScenarios) {
    $enabled = @(Get-KitClosure (@($requiredKits) + @($scenario.kits)) $kitMap | Sort-Object)
    $recipe = New-TestRecipe $scenario.name $enabled @($scenario.nav)
    $recipePath = Join-Path $recipeDir "$($scenario.name).recipe.json"
    $planPath = Join-Path $planDir "$($scenario.name).resolved-plan.json"
    Write-JsonUtf8 $recipePath $recipe

    & (Join-Path $ProjectRoot "tools\validate-recipe.ps1") `
        -ProjectRoot $ProjectRoot `
        -RecipePath ($recipePath.Substring($ProjectRoot.Length + 1)) | Out-Null

    & (Join-Path $ProjectRoot "tools\resolve-recipe.ps1") `
        -ProjectRoot $ProjectRoot `
        -RecipePath ($recipePath.Substring($ProjectRoot.Length + 1)) `
        -OutputPath ($planPath.Substring($ProjectRoot.Length + 1)) | Out-Null

    $plan = Read-JsonUtf8 $planPath
    Assert-ResolvedPlan $plan $enabled $scenario.name

    Assert-DaihuiDbPlan $ProjectRoot ($planPath.Substring($ProjectRoot.Length + 1)) $scenario.name

    $assemblyContractChecked = @("required-only", "import-flow", "analytics", "generic-forms", "all-site-no-mod", "all-site-with-mod").Contains([string]$scenario.name)
    if ($assemblyContractChecked) {
        Assert-AssemblyContract $ProjectRoot ($planPath.Substring($ProjectRoot.Length + 1)) $scenario.name $enabled
    }

    if ($AssembleAll) {
        $assemblyOutput = "build\kit-combination-tests\assembled-$($scenario.name)"
        & (Join-Path $ProjectRoot "tools\assemble-system.ps1") `
            -ProjectRoot $ProjectRoot `
            -ResolvedPlanPath ($planPath.Substring($ProjectRoot.Length + 1)) `
            -OutputDirectory $assemblyOutput | Out-Null
        & (Join-Path $ProjectRoot "tools\validate-generated-system.ps1") `
            -ProjectRoot $ProjectRoot `
            -GeneratedSystemDirectory $assemblyOutput | Out-Null
    }

    $summary.Add([ordered]@{
        name = [string]$scenario.name
        requestedOptionalKits = @($scenario.kits)
        resolvedKits = @($plan.resolvedKitOrder)
        assemblyContractChecked = [bool]$assemblyContractChecked
        fullAssemblyChecked = [bool]$AssembleAll
    })
}

$combinationCount = [math]::Pow(2, $optionalKits.Count)
if ($combinationCount -gt [int]::MaxValue) {
    throw "Too many optional kit combinations to enumerate"
}

for ($mask = 0; $mask -lt [int]$combinationCount; $mask++) {
    $selectedOptional = New-Object System.Collections.Generic.List[string]
    for ($i = 0; $i -lt $optionalKits.Count; $i++) {
        if (($mask -band (1 -shl $i)) -ne 0) {
            $selectedOptional.Add($optionalKits[$i])
        }
    }

    $enabled = @(Get-KitClosure (@($requiredKits) + @($selectedOptional)) $kitMap | Sort-Object)
    $name = "combo-$($mask.ToString('000'))"
    $recipe = New-TestRecipe $name $enabled @()
    $recipePath = Join-Path $recipeDir "$name.recipe.json"
    $planPath = Join-Path $planDir "$name.resolved-plan.json"
    Write-JsonUtf8 $recipePath $recipe

    & (Join-Path $ProjectRoot "tools\validate-recipe.ps1") `
        -ProjectRoot $ProjectRoot `
        -RecipePath ($recipePath.Substring($ProjectRoot.Length + 1)) | Out-Null

    & (Join-Path $ProjectRoot "tools\resolve-recipe.ps1") `
        -ProjectRoot $ProjectRoot `
        -RecipePath ($recipePath.Substring($ProjectRoot.Length + 1)) `
        -OutputPath ($planPath.Substring($ProjectRoot.Length + 1)) | Out-Null

    $plan = Read-JsonUtf8 $planPath
    Assert-ResolvedPlan $plan $enabled $name
}

$summaryPath = Join-Path $outputFullPath "kit-combination-summary.json"
[ordered]@{
    generatedAt = (Get-Date).ToString("s")
    manifest = $ManifestPath
    daihuiSampleDirectory = $DaihuiSampleDirectory
    requiredKits = $requiredKits
    optionalKits = $optionalKits
    exhaustiveCombinationCount = [int]$combinationCount
    capabilityScenarios = $summary.ToArray()
} | ConvertTo-Json -Depth 50 | Set-Content -Encoding UTF8 $summaryPath

Write-Host "OK kit combination tests"
Write-Host "  Required kits: $($requiredKits -join ', ')"
Write-Host "  Optional kits: $($optionalKits.Count)"
Write-Host "  Exhaustive combinations resolved: $([int]$combinationCount)"
Write-Host "  Capability assembly contracts checked: $(@($summary | Where-Object { $_.assemblyContractChecked }).Count)"
if ($AssembleAll) {
    Write-Host "  Full assemblies checked: $(@($summary | Where-Object { $_.fullAssemblyChecked }).Count)"
}
Write-Host "  Daihui samples: 5 CSV files, 5 data rows"
